### ISSUE TITLE
AttributeError: Can't get attribute 'LearnedPositionalEmbedding' on <module 'transformers.models.bart.modeling_bart' from 'E:\\conda\\envs\\style\\lib\\site-packages\\transformers\\models\\bart\\modeling_bart.p y'>

### ISSUE THREAD

**Issue by zhenpengguo** [kxz18/Stylized-Story-Generation-with-Style-Guided-Planning#1]
When I try to run the test code, the program reports an error: ”AttributeError: Can't get attribute 'LearnedPositionalEmbedding' on <module 'transformers.models.bart.modeling_bart' .... ”  I'm sure I've installed all the packages as requested in the requirements.txt file, but it says that I've installed the wrong attribute for the transformers package, I checked all the attributes for transformers==4.5.1 and found that there is no 'LearnedPositionalEmbedding' attribute, how can I solve this situation?

**Comment by kxz18** [comment]
Could you please provide the traceback of this error?

**Comment by zhenpengguo** [comment]
```
==========Configuration==========
Namespace(batch_size=32, mode='min', model='./bart_baseline.pth', test_set='../data/ROCStories_test.csv')
==========Loading test set==========
Cache found, directly loading data...
==========Loading model==========
Traceback (most recent call last):
  File "test.py", line 123, in <module>
    model = torch.load(args.model)
  File "E:\conda\envs\style\lib\site-packages\torch\serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "E:\conda\envs\style\lib\site-packages\torch\serialization.py", line 851, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'LearnedPositionalEmbedding' on <module 'transformers.models.bart.modeling_bart' from 'E:\\conda\\envs\\style\\lib\\site-packages\\transformers\\models\\bart\\modeling_bart.p
y'>
```

'''''''''''''''''''''''''''''''''''''''''''''''''
Maybe there is a problem with the torch? But what I have installed  torch==1.8.1

**Comment by kxz18** [comment]
Did you train with one version of transformers and test with another? It seems that when you stored the model to './bart_baseline.pth' there is 'LearnedPositionalEmbedding' in the bart module but there is no such attribute in the current transformers.
